@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing changes...
git commit -m "Initial commit for Netlify deployment"
echo Adding remote origin...
git remote add origin https://github.com/asadunanidawakhana/Alimranmisalipublicschool.git
echo Pushing to GitHub (main branch)...
git branch -M main
git push -u origin main
echo Done!
pause
